---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: airflow
  labels:
    release: prometheus-operator
spec:
  groups:
  - name: Airflow
    rules:
    - alert: AirflowTaskFailure
      expr: (changes(af_agg_ti_finish{dag_id!="oracle_price",state="failed"}[1d]) > 0) unless (changes(af_agg_ti_finish{dag_id!="oracle_price",state="success"}[1d]) > 0)
      for: 1m
      labels:
        severity: warning
        tier: application
        application: airflow
      annotations:
        summary: "Airflow task failed: {{ "{{$labels.task_name}}" }}"
        description: "Task '{{ "{{$labels.task_id}}" }}' in DAG '{{ "{{$labels.dag_id}}" }}' failed."
        runbook_url: https://runbooks.extratools.works
        dashboard: https://radixdlt.grafana.net/d/lFXqBGxWk/poc3a-airflow-cluster-dashboard?orgId=1&refresh=5s&var-prometheus=FQomEQz4k&var-namespace=airflow-prod&var-dag_id=All&var-task_id=All&var-loki=6OqgV0p4z
    - alert: OracleTaskFailure
      expr: (changes(af_agg_ti_finish{dag_id="oracle_price",state="failed"}[2m]) > 0) unless (changes(af_agg_ti_finish{dag_id="oracle_price",state="success"}[1m]) > 0)
      for: 2m
      labels:
        severity: warning
        tier: application
        application: airflow
      annotations:
        summary: "Oracle task failed: {{ "{{$labels.task_name}}" }}"
        description: "Task '{{ "{{$labels.task_id}}" }}' in DAG '{{ "{{$labels.dag_id}}" }}' failed."
        runbook_url: https://runbooks.extratools.works
        dashboard: https://radixdlt.grafana.net/d/lFXqBGxWk/poc3a-airflow-cluster-dashboard?orgId=1&refresh=5s&var-prometheus=FQomEQz4k&var-namespace=airflow-prod&var-dag_id=All&var-task_id=All&var-loki=6OqgV0p4z
 
    - alert: AirflowDAGFailure
      expr: (changes(af_agg_dagrun_duration_failed_count[1d]) > 0) unless (changes(af_agg_dagrun_duration_success_count[1d]) > 0)
      for: 1m
      labels:
        severity: warning
        tier: application
        application: airflow
      annotations:
        summary: "Airflow DAG failed: {{ "{{$labels.dag_id}}" }}"
        description: "DAG '{{ "{{$labels.dag_id}}" }}' failed."
    
    - alert: OraclePriceDAGFailure
      expr: (changes(af_agg_dagrun_duration_failed_count{dag_id="oracle_price"}[2m]) > 0) unless (changes(af_agg_dagrun_duration_success_count{dag_id="oracle_price"}[1m]) > 0)
      for: 2m
      labels:
        severity: critical
        tier: application
        application: airflow
      annotations:
        summary: "Oracle Price DAG failed: {{ "{{$labels.dag_id}}" }}"
        description: "DAG '{{ "{{$labels.dag_id}}" }}' failed."

    - alert: AirflowDAGImportErrors
      expr: airflow_dag_processing_import_errors > 0
      for: 10m
      labels:
        severity: warning
        tier: application
        application: airflow
      annotations:
        summary: "Airflow DAG import errors on DAG {{ "{{$labels.dag_id}}" }}"
        description: "DAG '{{ "{{$labels.dag_id}}" }}' import errored."

    - alert: AirflowSlowDAGProcessing
      expr: af_agg_dag_processing_duration{quantile="0.9"} > 10
      for: 5m
      labels:
        severity: warning
        tier: application
        application: airflow
      annotations:
        summary: "Slow DAG processing on {{ "{{$labels.dag_id}}" }}"
        description: "DAG '{{ "{{$labels.dag_id}}" }}' processing time is over 10secs."

    - alert: AirflowHighOperatorFailures
      expr: changes(airflow_operator_failures[2m]) > 5
      for: 2m
      labels:
        severity: warning
        tier: application
        application: airflow
      annotations:
        summary: "High rate of operator failures"
        description: "Airflow operator reports more than 5 failures/sec"

    - alert: AirflowSlowTasks
      expr: af_agg_dag_task_duration{quantile="0.9"} > 30
      for: 2m
      labels:
        severity: warning
        tier: application
        application: airflow
      annotations:
        summary: "Slow Airflow task execution for {{ "{{$labels.dag_id}}" }} {{ "{{$labels.task_id}}" }}"
        description: "Task execution time is over 30 seconds on the 90th percentile"
  - name: TokenPrice
    rules:
    - alert: TokenPriceIngressHighErrorRate
      expr: sum(rate(nginx_ingress_controller_requests{status=~'5..', ingress="token-price"}[1m])) by (path) / sum(rate(nginx_ingress_controller_requests{ingress="token-price"}[1m])) by (path) > 50
      for: 5m
      labels:
        severity: critical
        tier: application
        application: token-price
      annotations:
        summary: "High number of 5xx errors on the token-price requests"
        description: "High number of 5xx errors on the token-price requests"
        runbook_url: https://runbooks.extratools.works
        dashboard: https://radixdlt.grafana.net/d/lFXqBGxWk/poc3a-airflow-cluster-dashboard?orgId=1&refresh=5s&var-prometheus=FQomEQz4k&var-namespace=airflow-prod&var-dag_id=All&var-task_id=All&var-loki=6OqgV0p4z
    - alert: TokenPriceIngressHighLatency
      expr: histogram_quantile(0.95,sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress="token-price"}[5m])) by (le,ingress)) > 2
      for: 5m
      labels:
        severity: critical
        tier: application
        application: token-price
      annotations:
        summary: "High latency on the token-price requests"
        description: "The p95 response times are over 2 seconds"
        runbook_url: https://runbooks.extratools.works
        dashboard: https://radixdlt.grafana.net/d/lFXqBGxWk/poc3a-airflow-cluster-dashboard?orgId=1&refresh=5s&var-prometheus=FQomEQz4k&var-namespace=airflow-prod&var-dag_id=All&var-task_id=All&var-loki=6OqgV0p4z
    - alert: TokenPriceIngressHighRequestRate
      expr: sum(rate(nginx_ingress_controller_requests{ingress="token-price"}[5m])) > 500
      for: 5m
      labels:
        severity: warning
        tier: application
        application: token-price
      annotations:
        summary: "High number of incoming requests"
        description: "There are more than 500 req/s on token price"
        runbook_url: https://runbooks.extratools.works
        dashboard: https://radixdlt.grafana.net/d/lFXqBGxWk/poc3a-airflow-cluster-dashboard?orgId=1&refresh=5s&var-prometheus=FQomEQz4k&var-namespace=airflow-prod&var-dag_id=All&var-task_id=All&var-loki=6OqgV0p4z