---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: airflow
  labels:
    release: prometheus-operator
spec:
  groups:
  - name: Airflow
    rules:
    - alert: AirflowTaskFailure
      expr: (changes(airflow_task_status{dag_id!~"oracle_price|radix_charts_current_price|radix_charts_tokens_list",status="failed"}[1d]) > 0) unless (changes(airflow_task_status{dag_id!~"oracle_price|radix_charts_current_price|radix_charts_tokens_list",status="success"}[1d]) > 0)
      for: 1m
      labels:
        severity: warning
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Airflow task failed: {{ "{{$labels.task_name}}" }}"
        description: "Task '{{ "{{$labels.task_id}}" }}' in DAG '{{ "{{$labels.dag_id}}" }}' failed."
        runbook_url: https://runbooks.extratools.works
        dashboard: {{ .Values.alerts.dashboard_url }}
        app_url: "{{ .Values.ui_url }}/dags/{{ "{{$labels.dag_id}}" }}/grid?num_runs=25"

    - alert: OracleTaskFailure
      expr: (changes(airflow_task_status{dag_id="oracle_price",status="failed"}[2m]) > 0) unless (changes(airflow_task_status{dag_id="oracle_price",status="success"}[1m]) > 0)
      for: 2m
      labels:
        severity: warning
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Oracle task failed: {{ "{{$labels.task_name}}" }}"
        description: "Task '{{ "{{$labels.task_id}}" }}' in DAG '{{ "{{$labels.dag_id}}" }}' failed."
        runbook_url: https://runbooks.extratools.works
        dashboard: {{ .Values.alerts.dashboard_url }}
        app_url: "{{ .Values.ui_url }}/dags/{{ "{{$labels.dag_id}}" }}/grid?num_runs=25"
    
    - alert: RadixChartsCurrentPriceTaskFailure
      expr: (changes(airflow_task_status{dag_id="radix_charts_current_price",status="failed"}[2m]) > 0) unless (changes(airflow_task_status{dag_id="radix_charts_current_price",status="success"}[1m]) > 0)
      for: 2m
      labels:
        severity: warning
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Radix Charts current price task failed: {{ "{{$labels.task_name}}" }}"
        description: "Task '{{ "{{$labels.task_id}}" }}' in DAG '{{ "{{$labels.dag_id}}" }}' failed."
        runbook_url: https://runbooks.extratools.works
        dashboard: {{ .Values.alerts.dashboard_url }}
        app_url: "{{ .Values.ui_url }}/dags/{{ "{{$labels.dag_id}}" }}/grid?num_runs=25"
    - alert: AirflowDAGFailure
      expr: (airflow_dag_last_status{dag_id!="oracle_price",status="failed"} > 0)
      for: 1m
      labels:
        severity: warning
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Airflow DAG failed: {{ "{{$labels.dag_id}}" }}"
        description: "DAG '{{ "{{$labels.dag_id}}" }}' failed."
        app_url: "{{ .Values.ui_url }}/dags/{{ "{{$labels.dag_id}}" }}/grid?num_runs=25"
        dashboard: {{ .Values.alerts.dashboard_url }}

    - alert: OraclePriceDAGFailure
      expr: (airflow_dag_last_status{dag_id="oracle_price",status="failed"} > 0)
      for: 2m
      labels:
        severity: warning
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Oracle Price DAG failed: {{ "{{$labels.dag_id}}" }}"
        description: "DAG '{{ "{{$labels.dag_id}}" }}' failed."
        app_url: "{{ .Values.ui_url }}/dags/{{ "{{$labels.dag_id}}" }}/grid?num_runs=25"
        dashboard: {{ .Values.alerts.dashboard_url }}

    - alert: WatchdogDAGFailure
      expr: increase(dag_watchdog_custom_counter_passed[1m]) == 0
      labels:
        severity: warning
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Watchdog DAG failed: {{ "{{$labels.dag_id}}" }}"
        description: "DAG '{{ "{{$labels.dag_id}}" }}' failed."
        app_url: "{{ .Values.ui_url }}/dags/{{ "{{$labels.dag_id}}" }}/grid?num_runs=25"
        dashboard: {{ .Values.alerts.dashboard_url }}

    - alert: WatchdogDAGFailure
      expr: increase(dag_watchdog_custom_counter_passed[1m]) == 0
      for: 10m
      labels:
        severity: critical
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Watchdog DAG failed: {{ "{{$labels.dag_id}}" }}"
        description: "DAG '{{ "{{$labels.dag_id}}" }}' failed."
        app_url: "{{ .Values.ui_url }}/dags/{{ "{{$labels.dag_id}}" }}/grid?num_runs=25"
        dashboard: {{ .Values.alerts.dashboard_url }}

    - alert: AirflowDAGImportErrors
      expr: airflow_dag_processing_import_errors > 0
      for: 10m
      labels:
        severity: warning
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Airflow DAG import errors on DAG {{ "{{$labels.dag_id}}" }}"
        description: "DAG '{{ "{{$labels.dag_id}}" }}' import errored."
        app_url: "{{ .Values.ui_url }}/dags/{{ "{{$labels.dag_id}}" }}/grid?num_runs=25"
        dashboard: {{ .Values.alerts.dashboard_url }}

    - alert: AirflowSlowDAGProcessing
      expr: af_agg_dag_processing_duration{quantile="0.9"} > 10
      for: 5m
      labels:
        severity: warning
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Slow DAG processing on {{ "{{$labels.dag_id}}" }}"
        description: "DAG '{{ "{{$labels.dag_id}}" }}' processing time is over 10secs."
        app_url: "{{ .Values.ui_url }}/dags/{{ "{{$labels.dag_id}}" }}/grid?num_runs=25"
        dashboard: {{ .Values.alerts.dashboard_url }}

    - alert: AirflowHighOperatorFailures
      expr: changes(airflow_operator_failures[2m]) > 5
      for: 2m
      labels:
        severity: warning
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "High rate of operator failures"
        description: "Airflow operator reports more than 5 failures/sec"
        dashboard: {{ .Values.alerts.dashboard_url }}

    - alert: AirflowSlowTasks
      expr: af_agg_dag_task_duration{quantile="0.9"} > 30
      for: 2m
      labels:
        severity: warning
        tier: application
        application: airflow
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Slow Airflow task execution for {{ "{{$labels.dag_id}}" }} {{ "{{$labels.task_id}}" }}"
        description: "Task execution time is over 30 seconds on the 90th percentile"
        app_url: "{{ .Values.ui_url }}/dags/{{ "{{$labels.dag_id}}" }}/grid?num_runs=25"
        dashboard: {{ .Values.alerts.dashboard_url }}

  - name: TokenPrice
    rules:
    - alert: TokenPriceIngressHighErrorRate
      expr: sum(rate(nginx_ingress_controller_requests{status=~'5..', ingress="token-price"}[1m])) by (path) / sum(rate(nginx_ingress_controller_requests{ingress="token-price"}[1m])) by (path) > 50
      for: 5m
      labels:
        severity: critical
        tier: application
        application: token-price
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "High number of 5xx errors on the token-price requests"
        description: "High number of 5xx errors on the token-price requests"
        runbook_url: https://runbooks.extratools.works
        dashboard: {{ .Values.alerts.dashboard_url }}

    - alert: TokenPriceIngressHighLatency
      expr: histogram_quantile(0.95,sum(rate(token_price_request_duration_without_lsus_bucket[5m])) by (le)) > 2
      for: 5m
      labels:
        severity: critical
        tier: application
        application: token-price
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "High latency on the token-price requests"
        description: "The p95 response times are over 2 seconds"
        runbook_url: https://runbooks.extratools.works
        dashboard: {{ .Values.alerts.dashboard_url }}

    - alert: TokenPriceIngressHighRequestRate
      expr: sum(rate(nginx_ingress_controller_requests{ingress="token-price"}[5m])) > 500
      for: 5m
      labels:
        severity: warning
        tier: application
        application: token-price
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "High number of incoming requests"
        description: "There are more than 500 req/s on token price"
        runbook_url: https://runbooks.extratools.works
        dashboard: {{ .Values.alerts.dashboard_url }}
    - alert: OracleDAGExternalServiceFetchFailed
      expr: sum by (external_service) (rate(oracle_fetch_api_status{namespace="{{ .Release.Namespace }}", status="failed"}[5m])) > 0
      for: 5m
      labels:
        severity: critical
        tier: application
        application: token-price
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Oracle DAG, call to external service {{ "{{$labels.external_service}}" }} "
        description: "Oracle DAG, call to external service {{ "{{$labels.external_service}}" }} "
        runbook_url: https://runbooks.extratools.works
        dashboard: {{ .Values.alerts.dashboard_url }} 
    - alert: OracleDAGTokenUpdateFailures
      expr: sum by (symbol) (rate(oracle_update_token_status{status="missed"}[5m])) > 2
      for: 5m
      labels:
        severity: critical
        tier: application
        application: token-price
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: "Oracle DAG, call to external service {{ "{{$labels.symbol}}" }} "
        description: "Oracle DAG, call to external service {{ "{{$labels.symbol}}" }} "
        runbook_url: https://runbooks.extratools.works
        dashboard: {{ .Values.alerts.dashboard_url }} 

{{- if .Values.alerts.aws_infrastructure_enabled }}

  - name: TokenPriceRDS
    rules:
    - alert: RDSCpuUtilizationHigh
      expr: aws_rds_cpuutilization_average *on(dbinstance_identifier) group_left(tag_radixdlt_rds_cluster) aws_resource_info{dbinstance_identifier=~"{{ .Release.Namespace }}.*"} > 80
      for: 15m
      labels:
        severity: warning
        tier: application
        application: token-price
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: {{`"High CPU utilization for {{ $labels.dbinstance_identifier }} instance."`}}
        description: {{`"The CPU utilization of RDS {{ $labels.dbinstance_identifier }} instance is over 80% for 15mins."`}}
        dashboard: {{ .Values.alerts.dashboard_url }}
        runbook_url: "https://runbooks.extratools.works"

    - alert: RDSCpuUtilizationCritical
      expr: aws_rds_cpuutilization_average *on(dbinstance_identifier) group_left(tag_radixdlt_rds_cluster) aws_resource_info{dbinstance_identifier=~"{{ .Release.Namespace }}.*"} > 90
      for: 15m
      labels:
        severity: warning
        tier: application
        application: token-price
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: {{`"High CPU utilization for {{ $labels.dbinstance_identifier }} instance."`}}
        description: {{`"The CPU utilization of RDS {{ $labels.dbinstance_identifier }} instance is over 90% for 15mins."`}}
        dashboard: {{ .Values.alerts.dashboard_url }}
        runbook_url: "https://runbooks.extratools.works"

    - alert: RDSLowFreeRamHigh
      expr: aws_rds_freeable_memory_average *on(dbinstance_identifier) group_left(tag_radixdlt_rds_cluster) aws_resource_info{dbinstance_identifier=~"{{ .Release.Namespace }}.*"} < {{ .Values.alerts.free_rds_ram_warning_threshold_in_bytes }}
      for: 15m
      labels:
        severity: warning
        tier: application
        application: token-price
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: {{`"Low free RAM for {{ $labels.dbinstance_identifier }} instance."`}}
        description: "RDS instance is having less than {{ .Values.alerts.free_rds_ram_warning_threshold }} for 15mins"
        dashboard: {{ .Values.alerts.dashboard_url }}
        runbook_url: "https://runbooks.extratools.works"

    - alert: RDSLowFreeRamCritical
      expr: aws_rds_freeable_memory_average *on(dbinstance_identifier) group_left(tag_radixdlt_rds_cluster) aws_resource_info{dbinstance_identifier=~"{{ .Release.Namespace }}.*"} < {{ .Values.alerts.free_rds_ram_critical_threshold_in_bytes }}
      for: 15m
      labels:
        severity: warning
        tier: application
        application: token-price
        namespace: {{ .Release.Namespace }}
        cluster: {{ .Values.alerts.labels.cluster }}
        env: {{ .Values.alerts.labels.env }}
      annotations:
        summary: {{`"Low free RAM for {{ $labels.dbinstance_identifier }} instance."`}}
        description: "RDS instance is having less than {{ .Values.alerts.free_rds_ram_critical_threshold }} for 15mins"
        dashboard: {{ .Values.alerts.dashboard_url }}
        runbook_url: "https://runbooks.extratools.works"

{{- end }}