{{- range .Values.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .external_secret_name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
{{- if .aws_secret_key }}
  data:
    - secretKey: {{ .k8s_secret_data_key }}
      remoteRef:
        key: {{ .aws_secret_name }}
        property: {{ .aws_secret_key }}

{{- else if and (not .aws_secret_key) .k8s_secret_data_key }}
  data:
    - secretKey: {{ .k8s_secret_data_key }}
      remoteRef:
        key: {{ .aws_secret_name }}

{{- else if and (not .aws_secret_key) (not .k8s_secret_data_key) }}
  dataFrom:
    - extract:
        key: {{ .aws_secret_name }}

{{- else }}
{{- fail "Either aws_secret_key or k8s_secret_data_key must be provided" }}
{{- end }}
{{- end }}