helmDefaults:
  verify: false
  wait: false
  timeout: 600
  recreatePods: false
  force: false
  createNamespace: false
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: stable
    url: https://charts.helm.sh/stable
  - name: apache-airflow
    url: https://airflow.apache.org
  - name: rdx-works
    url: https://raw.githubusercontent.com/radixdlt/helm-charts/master/
    username: {{ requiredEnv "HELM_GH_USER" }}
    password: {{ requiredEnv "HELM_GH_PASS" }}
environments:
  dev: {}
  pr: {}
  prod: {}
releases:
  - name: airflow
    chart: apache-airflow/airflow
    version: 1.11.0
    values:
      - airflowVersion: "2.0.2"
      - images:
          airflow:
            repository: radixdlt/airflow
            tag: {{ .StateValues.ci.AIRFLOW_IMAGE_TAG }}
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl
    set:
  - name: airflow-resources
    chart: ./airflow-resources
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl
