version: "3.7"

services:
  app:
    image: pepe
    environment:
      DB_PASSWORD: postgres
    ports:
      - 8000:8000
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    volumes:
      - ./sample_data/:/postgres
    ports:
      - 5432:5432
