version: "3.7"

services:
  app:
    build:
      context: .
    entrypoint: uvicorn app.main:app --workers 4 --host 0.0.0.0 --port 8000 --log-level info --reload
    environment:
      DB_HOST: airflow-postgresql
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: dags
    ports:
      - 8000:8000
      - 5990:5990
    volumes:
      - ./app/:/app
    networks:
      - airflow_network

networks:
  airflow_network:
    external: true
    name: airflow_default
