repositories:
  - name: apache-airflow
    url: https://airflow.apache.org

releases:
  - name: airflow
    namespace: airflow
    chart: apache-airflow/airflow
    version: 1.11.0
    values:
      - images:
          airflow:
            repository: radixdlt/airflow
            tag: sha-4ea6cd3
      - registry:
          secretName: docker-hub-dev
      - workers:
          extraInitContainers:
            - name: db-migrations
              image: radixdlt/airflow-migration:sha-87a5403
              env:
                - name: DB_HOST
                  value: "airflow-postgresql"
                - name: DB_USER
                  value: "postgres"
                - name: DB_PASSWORD
                  value: "postgres"
                - name: DB_NAME
                  value: "token_price"
      - env:
          - name: DB_HOST
            value: "airflow-postgresql"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "postgres"
          - name: DB_NAME
            value: "token_price"
      - ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: airflow.rdx-works-main.extratools.works
              paths:
                - path: /
                  pathType: Prefix
    set:
