helmDefaults:
  verify: false
  wait: true
  timeout: 600
  recreatePods: false
  force: false
  createNamespace: false

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: stable
    url: https://charts.helm.sh/stable
  - name: rdx-works
    url: https://raw.githubusercontent.com/radixdlt/helm-charts/master/
    username: {{ requiredEnv "HELM_GH_USER" }}
    password: {{ requiredEnv "HELM_GH_PASS" }}

environments:
  default: {}
  dev: {}
  pr: {}
  prod: {}
releases:
  - name: token-price
    chart: ./token-price
    values:
      - environments/{{ .Environment.Name }}/token-price-values.yaml.gotmpl

  - name: postgres
    chart: bitnami/postgresql
    installed: {{ .StateValues | get "ci.useLocalDb" "false" }}
    version: 12.1.5
    values:
      - auth:
          postgresPassword: secret@123
          database: "token-price"
      - primary:
          persistence:
            enabled: false

  - name: alertmanager
    chart: rdx-works/alertmanager-configs
    version: 1.1.0
    installed: {{ ne .Environment.Name "pr" }}
    values:
      - environments/{{ .Environment.Name }}/alertmanager.yaml.gotmpl

  - name: developer-access
    chart: rdx-works/developer-access
    version: 1.0.0
    values:
      - project: token-price
      - environments/{{ .Environment.Name }}/developer-access.yaml.gotmpl
