from os import getenv


class Config:
    RADIX_TOKEN = "XRD"

    RADIX_CHARTS_TOKENS_PRICE_LIST = "https://api.radixapi.net/v1/token/price/list"
    RADIX_CHARTS_TOKEN_PRICE_CURRENT = "https://api.radixapi.net/v1/token/price/current"
    RADIX_CHARTS_AUTHORIZATION_TOKEN = getenv("RADIX_CHARTS_AUTHORIZATION_TOKEN")

    DB_URI = getenv("DB_URI")

    NETWORK_ID = int(getenv("NETWORK_ID", 2))
    NETWORK_GATEWAY = getenv("NETWORK_GATEWAY", "https://stokenet.radixdlt.com")

    COINMARKETCAP_DEV_API_KEY = getenv("COINMARKETCAP_DEV_API_KEY")
    COIN_GECKO_API = getenv("COIN_GECKO_API", "https://api.coingecko.com/api/v3")
    COIN_GECKO_API_KEY = getenv("COIN_GECKO_API_KEY", "")

    ORACLE_SCHEDULE_INTERVAL = getenv("ORACLE_SCHEDULE_INTERVAL", None)
    ORACLE_COIN_GECKO_IDS = "radix,bitcoin,ethereum,tether,usd-coin"
    ORACLE_CMC_PAIRS = "BTC/XRD,ETH/XRD,USDT/XRD,USDC/XRD"
    ORACLE_PRICE_DIFF_TRIGGER = 0.05
    ORACLE_LOCK_FEE_ADDRESS = getenv(
        "ORACLE_LOCK_FEE_ADDRESS",
        "component_tdx_2_1cptxxxxxxxxxfaucetxxxxxxxxx000527798379xxxxxxxxxyulkzl",
    )
    ORACLE_LOCK_FEE = float(getenv("ORACLE_LOCK_FEE", 0.58434484845))
    ORACLE_CONFIG_FILE = getenv("ORACLE_CONFIG_FILE", "config-develop.json")

    TWITTER_RADIXDLT_API_KEY = getenv("TWITTER_RADIXDLT_API_KEY")
    TWITTER_RADIXDLT_API_KEY_SECRET = getenv("TWITTER_RADIXDLT_API_KEY_SECRET")
    TWITTER_RADIXDLT_ACCESS_TOKEN = getenv("TWITTER_RADIXDLT_ACCESS_TOKEN")
    TWITTER_RADIXDLT_ACCESS_TOKEN_SECRET = getenv(
        "TWITTER_RADIXDLT_ACCESS_TOKEN_SECRET"
    )
    TWITTER_RADIXDLT_BAERER_TOKEN = getenv("TWITTER_RADIXDLT_BAERER_TOKEN")
    TWITTER_SCRYPTOLANG_API_KEY = getenv("TWITTER_SCRYPTOLANG_API_KEY")
    TWITTER_SCRYPTOLANG_API_KEY_SECRET = getenv("TWITTER_SCRYPTOLANG_API_KEY_SECRET")
    TWITTER_SCRYPTOLANG_ACCESS_TOKEN = getenv("TWITTER_SCRYPTOLANG_ACCESS_TOKEN")
    TWITTER_SCRYPTOLANG_ACCESS_TOKEN_SECRET = getenv(
        "TWITTER_SCRYPTOLANG_ACCESS_TOKEN_SECRET"
    )
    TWITTER_SCRYPTOLANG_BAERER_TOKEN = getenv("TWITTER_SCRYPTOLANG_BAERER_TOKEN")
    GITHUB_TOKEN = getenv("GITHUB_TOKEN")
    TELEGRAM_RADIX_DLT_BOT_ID = getenv("TELEGRAM_RADIX_DLT_BOT_ID")
    TELEGRAM_RADIX_DLT_COMBOT_ID = getenv("TELEGRAM_RADIX_DLT_COMBOT_ID")
    TELEGRAM_RADIX_DLT_COMBOT_API_KEY = getenv("TELEGRAM_RADIX_DLT_COMBOT_API_KEY")
    TELEGRAM_RADIX_DEVS_BOT_ID = getenv("TELEGRAM_RADIX_DEVS_BOT_ID")
    TELEGRAM_RADIX_DEVS_COMBOT_ID = getenv("TELEGRAM_RADIX_DEVS_COMBOT_ID")
    TELEGRAM_RADIX_DEVS_COMBOT_API_KEY = getenv("TELEGRAM_RADIX_DEVS_COMBOT_API_KEY")

    REDDIT_CLIENT_ID = getenv("REDDIT_CLIENT_ID")
    REDDIT_CLIENT_SECRET = getenv("REDDIT_CLIENT_SECRET")
    REDDIT_USER_AGENT = getenv("REDDIT_USER_AGENT")
    REDDIT_REFRESH_TOKEN = getenv("REDDIT_REFRESH_TOKEN")

    BURNTRACKER_FIVE_BURN = (
        "https://burntracker.io/api/token/getFiveBurnData?symbol=XRD"
    )
    BURNTRACKER_BURNDATA = "https://burntracker.io/api/token/fetch_burndata_for_graph?decimal=18&symbol=XRD&type=Token&format=burn&range=24h"
    DEFILAMA_TVL = "https://api.llama.fi/v2/historicalChainTvl/Radix"
    RADIX_API_STATS = "https://api.radixapi.net/v1/network/statistics"
