from os import getenv
from urllib.parse import quote_plus


class Config:
    RADIX_CHARTS_TOKENS_PRICE_LIST = "https://api.radixapi.net/v1/token/price/list"
    RADIX_CHARTS_TOKEN_PRICE_CURRENT = "https://api.radixapi.net/v1/token/price/current"
    RADIX_CHARTS_AUTHORIZATION_TOKEN = getenv("RADIX_CHARTS_AUTHORIZATION_TOKEN")

    DB_URI = getenv("DB_URI")
    NETWORK_ID = getenv("NETWORK_ID", 2)
    NETWORK_GATEWAY = getenv(
        "NETWORK_GATEWAY", "https://stokenet.radixdlt.com/transaction/submit"
    )
    COINMARKETCAP_DEV_API_KEY = getenv("COINMARKETCAP_DEV_API_KEY")
    TWITTER_RADIXDLT_API_KEY = getenv("TWITTER_RADIXDLT_API_KEY")
    TWITTER_RADIXDLT_API_KEY_SECRET = getenv("TWITTER_RADIXDLT_API_KEY_SECRET")
    TWITTER_RADIXDLT_ACCESS_TOKEN = getenv("TWITTER_RADIXDLT_ACCESS_TOKEN")
    TWITTER_RADIXDLT_ACCESS_TOKEN_SECRET = getenv(
        "TWITTER_RADIXDLT_ACCESS_TOKEN_SECRET"
    )
    TWITTER_RADIXDLT_BAERER_TOKEN = getenv("TWITTER_RADIXDLT_BAERER_TOKEN")
    TWITTER_SCRYPTOLANG_API_KEY = getenv("TWITTER_SCRYPTOLANG_API_KEY")
    TWITTER_SCRYPTOLANG_API_KEY_SECRET = getenv("TWITTER_SCRYPTOLANG_API_KEY_SECRET")
    TWITTER_SCRYPTOLANG_ACCESS_TOKEN = getenv("TWITTER_SCRYPTOLANG_ACCESS_TOKEN")
    TWITTER_SCRYPTOLANG_ACCESS_TOKEN_SECRET = getenv(
        "TWITTER_SCRYPTOLANG_ACCESS_TOKEN_SECRET"
    )
    TWITTER_SCRYPTOLANG_BAERER_TOKEN = getenv("TWITTER_SCRYPTOLANG_BAERER_TOKEN")
    GITHUB_TOKEN = getenv("GITHUB_TOKEN")
    TELEGRAM_RADIX_DLT_BOT_ID = getenv("TELEGRAM_RADIX_DLT_BOT_ID")
    TELEGRAM_RADIX_DLT_COMBOT_ID = getenv("TELEGRAM_RADIX_DLT_COMBOT_ID")
    TELEGRAM_RADIX_DLT_COMBOT_API_KEY = getenv("TELEGRAM_RADIX_DLT_COMBOT_API_KEY")
    TELEGRAM_RADIX_DEVS_BOT_ID = getenv("TELEGRAM_RADIX_DEVS_BOT_ID")
    TELEGRAM_RADIX_DEVS_COMBOT_ID = getenv("TELEGRAM_RADIX_DEVS_COMBOT_ID")
    TELEGRAM_RADIX_DEVS_COMBOT_API_KEY = getenv("TELEGRAM_RADIX_DEVS_COMBOT_API_KEY")
