{{- if not .Values.localDB.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secrets-formatted
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: connection
      remoteRef:
        key: {{ .Values.postgres.formatted.name }}
        property: connection
{{- end }}