{{- if not .Values.localDB.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: postgresqlUsername
      remoteRef:
        key: {{ .Values.postgres.secrets.credentials }}
        property: postgresqlUsername
    - secretKey: postgresql-password
      remoteRef:
        key: {{ .Values.postgres.secrets.credentials }}
        property: postgresql-password
{{- end }}