apiVersion: batch/v1
kind: Job
metadata:
  name: radixdlt-db-migrations
spec:
  backoffLimit: 2
  template:
    spec:
      imagePullSecrets:
        - name: docker-hub-dev
      containers:
      - name: radixdlt-db-migrations
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        env:
          - name: DB_URI
            {{- if .Values.dbUri }}
            value: {{ .Values.dbUri | quote }}
            {{- else }}
            valueFrom:
              secretKeyRef:
                name: dags-db-connection-string
                key: dags_db_connection_string
            {{- end }}
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
