replicaCount: 1

image:
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: "token-price"
fullnameOverride: "token-price"

metrics:
  enabled: false
  port: 5990
  serviceMonitor:
    enabled: false
    interval: 60s

serviceAccount:
  create: true
  annotations: {}
  name: "token-price"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  containerPort: 8000

ingress:
  enabled: true
  annotations:
  hosts: []

resources:
  limits:
    memory: 500Mi
  requests:
    cpu: 600m
    memory: 250Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

affinity: {}

env:

secrets: []
