"""add coingecko prices

Revision ID: 707a6defd36f
Revises: cdacc88493e7
Create Date: 2024-08-21 11:47:24.234496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import desc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "707a6defd36f"
down_revision: Union[str, None] = "cdacc88493e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "coingecko_token_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("price", sa.Float, nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("marketcap", sa.BigInteger(), nullable=False),
        sa.Column("weeklyMovingAvgPrice", sa.Float, nullable=False),
        sa.Column("weeklyMovingAvgVolume", sa.Float, nullable=False),
        sa.Column("weeklyMovingAvgMarketCap", sa.Float, nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("cg_token_update_date_idx"),
        "coingecko_token_prices",
        ["symbol", desc("last_updated_at")],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("cg_token_update_date_idx"), "coingecko_token_prices")
    op.drop_table("coingecko_token_prices")
    # ### end Alembic commands ###
