"""Add intex to latest price table

Revision ID: 70dce8c50c36
Revises: a63f581252f1
Create Date: 2025-02-25 16:56:59.770674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70dce8c50c36'
down_revision: Union[str, None] = 'a63f581252f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE UNIQUE INDEX idx_latest_token_prices_id ON radix_token_prices_latest (id);
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP INDEX idx_latest_token_prices_id;
        """
    )
    # ### end Alembic commands ###
