name: Airflow Continuous Integration

on:
  push:
    branches:
      - main
  release:
    types: [published]
permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: RDXWorks-actions/checkout@main
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
  tags:
    runs-on: ubuntu-latest
    outputs:
      airflow-tags: ${{ steps.docker-tags-airflow-service.outputs.tags }}
      airflow-labels: ${{ steps.docker-tags-airflow-service.outputs.labels }}
      airflow-json: ${{ steps.docker-tags-airflow-service.outputs.json }}
    steps:
      - uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0
      - name: Docker tags
        id: docker-tags-airflow-service
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: |
            ${{ vars.AWS_ECR_REGISTRY }}/airflow-service
          tags: |
            type=sha,event=pr
            type=sha,event=branch
            type=semver,pattern={{version}}

  build-airflow:
    needs:
    - tags
    uses: trellisarch/public-iac-reusable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: ${{ vars.AWS_ECR_REGISTRY }}
      image_organization: ""
      image_name: "airflow"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "airflow"
      dockerfile: "airflow/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      role_to_assume: ${{ github.event_name == 'release' && secrets.ECR_PUSHER_REPO_ROLE_RELEASE || secrets.ECR_PUSHER_REPO_ROLE_MAIN }}

  build-token-service:
    needs:
    - tags
    uses: trellisarch/public-iac-reusable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: ${{ vars.AWS_ECR_REGISTRY }}
      image_organization: ""
      image_name: "token-price-service"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "consumers/token-price-service"
      dockerfile: "consumers/token-price-service/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      role_to_assume: ${{ github.event_name == 'release' && secrets.ECR_PUSHER_REPO_ROLE_RELEASE || secrets.ECR_PUSHER_REPO_ROLE_MAIN }}

  build-airflow-migrations:
    needs:
    - tags
    uses: trellisarch/public-iac-reusable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: ${{ vars.AWS_ECR_REGISTRY }}
      image_organization: ""
      image_name: "airflow-migration"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "database"
      dockerfile: "database/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      role_to_assume: ${{ github.event_name == 'release' && secrets.ECR_PUSHER_REPO_ROLE_RELEASE || secrets.ECR_PUSHER_REPO_ROLE_MAIN }}
  
  run_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: RDXWorks-actions/checkout@main
      - name: run pytest unit test
        run: |
          cd airflow
          make ci-test


