name: Airflow Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
      - main
  release:
    types: [published]
permissions:
  id-token: write
  pull-requests: write
  contents: read
  deployments: write
  packages: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."

  tags:
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      airflow-tags: ${{ steps.docker-tags-airflow-service.outputs.tags }}
      airflow-labels: ${{ steps.docker-tags-airflow-service.outputs.labels }}
      airflow-json: ${{ steps.docker-tags-airflow-service.outputs.json }}
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0
      - name: Docker tags
        id: docker-tags-airflow-service
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: |
            docker.io/radixdlt/airflow-service
          tags: |
            type=sha,event=pr
            type=sha,event=branch
            type=semver,pattern={{version}}

  build-airflow:
    needs: 
    - tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "airflow"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "airflow"
      dockerfile: "airflow/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  build-token-service:
    needs: 
    - tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "token-price-service"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "consumers/token-price-service"
      dockerfile: "consumers/token-price-service/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}


  build-airflow-migrations:
    needs: 
    - tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "airflow-migration"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "database"
      dockerfile: "database/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  deploy-airflow-dev:
    if:  github.ref == 'refs/heads/develop'
    name: "Deploy Airflow Dev"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.15.0
    needs:
      - tags
      - build-airflow
      - build-airflow-migrations
      - build-token-service
    with:
      app_name: 'airflow'
      step_name: 'deploy-airflow-dev'
      env_name: dev
      namespace: airflow-dev
      helm_command: "apply"
      create_subns: false
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: arn:aws:iam::308190735829:role/gh-airflow-dev-deployer
      eks_cluster: rdx-works-main-dev
      helm_folder: "deploy/helm/airflow"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.environment=dev,
        ci.HF_CREATE_NAMESPACES=false,
        ci.AIRFLOW_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.AIRFLOW_MIGRATION_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.INSTALL_DB=${{ false }},
        ci.INSTALL_AIRFLOW=${{ true }},
        ci.INSTALL_TOKEN_SERVICE=${{ true }}

  deploy-airflow-prod:
    if:  github.ref == 'refs/heads/main'
    name: "Deploy Airflow Prod"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.15.0
    needs:
      - tags
      - build-airflow
      - build-airflow-migrations
      - build-token-service
    with:
      app_name: 'airflow'
      step_name: 'deploy-airflow-prod'
      env_name: prod
      namespace: airflow-prod
      helm_command: "apply"
      create_subns: false
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: arn:aws:iam::308190735829:role/gh-airflow-prod-deployer
      eks_cluster: rdx-works-main-prod
      helm_folder: "deploy/helm/airflow"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.environment=dev,
        ci.HF_CREATE_NAMESPACES=false,
        ci.AIRFLOW_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.AIRFLOW_MIGRATION_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.INSTALL_DB=${{ false }},
        ci.INSTALL_AIRFLOW=${{ true }},
        ci.INSTALL_TOKEN_SERVICE=${{ true }}

  deploy_pull_request_airflow:
    if: ${{ github.event.pull_request }}
    name: "Deploy PR airflow"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.15.0
    needs:
      - tags
      - build-airflow
      - build-airflow-migrations
      - build-token-service
    with:
      env_name: pr
      hierarchical_namespace: airflow-ci-pr
      namespace: airflow-pr-${{ github.event.number }}
      helm_command: "apply"
      create_subns: true
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: 'arn:aws:iam::308190735829:role/gh-airflow-pr-deployer'
      eks_cluster: rdx-works-main-dev
      helm_folder: "deploy/helm/airflow/"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.prNumber=${{ github.event.number }},
        ci.AIRFLOW_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.AIRFLOW_MIGRATION_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.INSTALL_DB=${{ contains(github.event.pull_request.labels.*.name, 'deploy-db') || contains(github.event.pull_request.labels.*.name, 'deploy-airflow') || contains(github.event.pull_request.labels.*.name, 'deploy-token-service') }},
        ci.INSTALL_AIRFLOW=${{ contains(github.event.pull_request.labels.*.name, 'deploy-airflow') }},
        ci.INSTALL_TOKEN_SERVICE=${{ contains(github.event.pull_request.labels.*.name, 'deploy-token-service') }}
      app_name: 'airflow'
      step_name: 'deploy-pr'
