name: Airflow Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  release:
    types: [published]
permissions:
  id-token: write
  pull-requests: write
  contents: read
  deployments: write
  packages: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."

  tags:
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      airflow-tags: ${{ steps.docker-tags-airflow-service.outputs.tags }}
      airflow-labels: ${{ steps.docker-tags-airflow-service.outputs.labels }}
      airflow-json: ${{ steps.docker-tags-airflow-service.outputs.json }}
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0
      - name: Docker tags
        id: docker-tags-airflow-service
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: |
            docker.io/radixdlt/airflow-service
          tags: |
            type=sha,event=pr
            type=sha,event=branch
            type=semver,pattern={{version}}

  build-airflow:
    needs: 
    - tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "airflow"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "airflow"
      dockerfile: "airflow/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  build-token-service:
    needs: 
    - tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "token-price-service"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "consumers/token-price-service"
      dockerfile: "consumers/token-price-service/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  build-airflow-migrations:
    needs: 
    - tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "airflow-migration"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "database"
      dockerfile: "database/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}
  
  fetch-airflow-dev-secrets:
    if:  github.ref == 'refs/heads/develop'
    name: "Fetch Airflow Dev secrets"
    needs:
      - tags
      - build-airflow
      - build-airflow-migrations
      - build-token-service
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      webserver-dev-username: ${{ steps.setup_outputs.outputs.webserver-dev-username }}
      webserver-dev-password: ${{ steps.setup_outputs.outputs.webserver-dev-password }}
    steps:
      - uses: RDXWorks-actions/checkout@main
      - uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
        with:
          role_name: ${{ secrets.AWS_ROLE_NAME_AIRFLOW_SECRETS }}
          app_name: 'airflow'
          step_name: 'airflow-webserver-secrets'
          secret_prefix: 'GH'
          secret_name: ${{ secrets.AWS_AIRFLOW_DEV_SECRET_ARN }}
          parse_json: true
      - name: Set outputs
        id: setup_outputs
        run: |
          echo "::set-output name=webserver-dev-username::${{ env.GH_WEBSERVER_USERNAME }}"
          echo "::set-output name=webserver-dev-password::${{ env.GH_WEBSERVER_PASSWORD }}"
          echo "WEBSERVER USERNAME: ${{ env.GH_WEBSERVER_USERNAME }}"
      - uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.15.0
        with:
          app_name: 'airflow'
          step_name: 'deploy-airflow-dev'
          env_name: dev
          namespace: airflow-dev
          helm_command: "apply"
          create_subns: false
          restart_pods: false
          aws_region: eu-west-2
          role_to_assume: arn:aws:iam::308190735829:role/gh-airflow-dev-deployer
          eks_cluster: rdx-works-main-dev
          helm_folder: "deploy/helm/airflow"
          helmfile_extra_vars: >-
            ci.tag=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
            ci.environment=dev,
            ci.HF_CREATE_NAMESPACES=false,
            ci.INSTALL_DB=${{ false }},
            ci.INSTALL_AIRFLOW=${{ true }},
            ci.INSTALL_TOKEN_SERVICE=${{ true }},
            ci.AIRFLOW_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
            ci.AIRFLOW_MIGRATION_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
            ci.AIRFLOW_WEBSERVER_USERNAME=${{ env.GH_WEBSERVER_USERNAME }},         
            ci.AIRFLOW_WEBSERVER_PASSWORD=${{ env.GH_WEBSERVER_PASSWORD }} 

  # deploy-airflow-dev:
  #   if:  github.ref == 'refs/heads/develop'
  #   name: "Deploy Airflow Dev"
  #   uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.15.0
  #   needs:
  #     - tags
  #     - build-airflow
  #     - build-airflow-migrations
  #     - build-token-service
  #     - fetch-airflow-dev-secrets
  #   with:
  #     app_name: 'airflow'
  #     step_name: 'deploy-airflow-dev'
  #     env_name: dev
  #     namespace: airflow-dev
  #     helm_command: "apply"
  #     create_subns: false
  #     restart_pods: false
  #     aws_region: eu-west-2
  #     role_to_assume: arn:aws:iam::308190735829:role/gh-airflow-dev-deployer
  #     eks_cluster: rdx-works-main-dev
  #     helm_folder: "deploy/helm/airflow"
  #     helmfile_extra_vars: >-
  #       ci.tag=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
  #       ci.environment=dev,
  #       ci.HF_CREATE_NAMESPACES=false,
  #       ci.INSTALL_DB=${{ false }},
  #       ci.INSTALL_AIRFLOW=${{ true }},
  #       ci.INSTALL_TOKEN_SERVICE=${{ true }},
  #       ci.AIRFLOW_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
  #       ci.AIRFLOW_MIGRATION_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
  #       ci.AIRFLOW_WEBSERVER_USERNAME=${{ needs.fetch-airflow-dev-secrets.outputs.webserver-dev-username }},         
  #       ci.AIRFLOW_WEBSERVER_PASSWORD=${{ needs.fetch-airflow-dev-secrets.outputs.webserver-dev-password }} 
  
  fetch-airflow-prod-secrets:
    if:  github.ref == 'refs/heads/main'
    name: "Fetch Airflow Prod secrets"
    runs-on: ubuntu-latest
    outputs:
      webserver-prod-username: ${{ env.GH_WEBSERVER_USERNAME }}
      webserver-prod-password: ${{ env.GH_WEBSERVER_PASSWORD }}
    permissions: write-all
    steps:
      - uses: RDXWorks-actions/checkout@main
      - uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
        with:
          role_name: ${{ secrets.AWS_ROLE_NAME_AIRFLOW_SECRETS }}
          app_name: 'airflow'
          step_name: 'airflow-webserver-secrets'
          secret_prefix: 'GH'
          secret_name: ${{ secrets.AWS_AIRFLOW_PROD_SECRET_ARN }}
          parse_json: true  

  deploy-airflow-prod:
    if:  github.ref == 'refs/heads/main'
    name: "Deploy Airflow Prod"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.15.0
    needs:
      - tags
      - build-airflow
      - build-airflow-migrations
      - build-token-service
      - fetch-airflow-prod-secrets
    with:
      app_name: 'airflow'
      step_name: 'deploy-airflow-prod'
      env_name: prod
      namespace: airflow-prod
      helm_command: "apply"
      create_subns: false
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: arn:aws:iam::308190735829:role/gh-airflow-prod-deployer
      eks_cluster: rdx-works-main-prod
      helm_folder: "deploy/helm/airflow"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.environment=prod,
        ci.HF_CREATE_NAMESPACES=false,
        ci.INSTALL_DB=${{ false }},
        ci.INSTALL_AIRFLOW=${{ true }},
        ci.INSTALL_TOKEN_SERVICE=${{ true }},
        ci.AIRFLOW_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.AIRFLOW_MIGRATION_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.AIRFLOW_WEBSERVER_USERNAME=${{ needs.fetch-airflow-prod-secrets.outputs.webserver-prod-username }},         
        ci.AIRFLOW_WEBSERVER_PASSWORD=${{ needs.fetch-airflow-prod-secrets.outputs.webserver-prod-password }} 

  deploy_pull_request_airflow:
    if: ${{ github.event.pull_request }}
    name: "Deploy PR airflow"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.15.0
    needs:
      - tags
      - build-airflow
      - build-airflow-migrations
      - build-token-service
    with:
      env_name: pr
      hierarchical_namespace: airflow-ci-pr
      namespace: airflow-pr-${{ github.event.number }}
      helm_command: "apply"
      create_subns: true
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: 'arn:aws:iam::308190735829:role/gh-airflow-pr-deployer'
      eks_cluster: rdx-works-main-dev
      helm_folder: "deploy/helm/airflow/"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.prNumber=${{ github.event.number }},
        ci.INSTALL_DB=${{ contains(github.event.pull_request.labels.*.name, 'deploy-db') || contains(github.event.pull_request.labels.*.name, 'deploy-airflow') || contains(github.event.pull_request.labels.*.name, 'deploy-token-service') }},
        ci.INSTALL_AIRFLOW=${{ contains(github.event.pull_request.labels.*.name, 'deploy-airflow') }},
        ci.INSTALL_TOKEN_SERVICE=${{ contains(github.event.pull_request.labels.*.name, 'deploy-token-service') }},
        ci.AIRFLOW_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.AIRFLOW_MIGRATION_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }}
      app_name: 'airflow'
      step_name: 'deploy-pr'