name: Airflow Database Migrations

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment Name'
        required: true
        type: choice
        options:
          - dev
          - prod
          - rtlj-prod

permissions:
  id-token: write
  pull-requests: write
  contents: read
  deployments: write
  packages: write

jobs:
  tags:
    runs-on: ubuntu-latest
    outputs:
      airflow-tags: ${{ steps.docker-tags-airflow-service.outputs.tags }}
      airflow-labels: ${{ steps.docker-tags-airflow-service.outputs.labels }}
      airflow-json: ${{ steps.docker-tags-airflow-service.outputs.json }}
    steps:
      - uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0
      - name: Docker tags
        id: docker-tags-airflow-service
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: |
            docker.io/radixdlt/airflow-service
          tags: |
            type=sha,event=pr
            type=sha,event=branch
            type=semver,pattern={{version}}

  build-airflow-migrations:
    needs:
    - tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "airflow-migration"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "database"
      dockerfile: "database/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  deploy-airflow-migrations-prod:
    if: github.event.inputs.environment == 'prod'
    name: "(PROD) Deploy Airflow Migrations"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@main
    needs:
      - tags
      - build-airflow-migrations
    with:
      app_name: 'airflow'
      step_name: 'deploy-airflow-prod'
      env_name: prod
      namespace: airflow-prod
      helm_command: "apply"
      create_subns: false
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: arn:aws:iam::308190735829:role/gh-airflow-prod-deployer
      eks_cluster: rdx-works-main-prod
      helm_folder: "deploy/helm/airflow"
      helm_chart: "db-migrations"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.environment=prod,
        ci.HF_CREATE_NAMESPACES=false,
        ci.AIRFLOW_MIGRATION_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.RUN_DB_MIGRATIONS=true

  deploy-airflow-migrations-rtlj-prod:
    if: github.event.inputs.environment == 'rtlj-prod'
    name: "(RTLJ-PROD) Deploy Airflow Migrations"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@main
    needs:
      - tags
      - build-airflow-migrations
    with:
      app_name: 'airflow'
      step_name: 'deploy-airflow-rtlj-prod'
      env_name: rtlj-prod
      namespace: airflow-prod
      helm_command: "apply"
      create_subns: false
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: arn:aws:iam::821496737932:role/gh-airflow-prod-deployer
      eks_cluster: rtlj-prod
      helm_folder: "deploy/helm/airflow"
      helm_chart: "db-migrations"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.environment=rtlj-prod,
        ci.HF_CREATE_NAMESPACES=false,
        ci.AIRFLOW_MIGRATION_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.RUN_DB_MIGRATIONS=true

  deploy-airflow-migrations-dev:
    if: github.event.inputs.environment == 'dev'
    name: "(DEV) Deploy Airflow Migrations"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@main
    needs:
      - tags
      - build-airflow-migrations
    with:
      app_name: 'airflow'
      step_name: 'deploy-airflow-dev'
      env_name: dev
      namespace: airflow-dev
      helm_command: "apply"
      create_subns: false
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: arn:aws:iam::308190735829:role/gh-airflow-dev-deployer
      eks_cluster: rdx-works-main-dev
      helm_folder: "deploy/helm/airflow"
      helm_chart: "db-migrations"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.environment=dev,
        ci.HF_CREATE_NAMESPACES=false,
        ci.AIRFLOW_MIGRATION_IMAGE_TAG=${{ fromJSON(needs.tags.outputs.airflow-json).labels['org.opencontainers.image.version'] }},
        ci.RUN_DB_MIGRATIONS=true
