name: CI token price service

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'consumers/token-price-service/**'
      - 'deploy/helm/token-price/**'
      - ".github/workflows/console-ci.yaml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'consumers/token-price-service/**'
      - 'deploy/helm/token-price/**'
      - ".github/workflows/console-ci.yaml"
  release:
    types: [published]

permissions:
  id-token: write
  pull-requests: write
  contents: read
  deployments: write
  packages: write

jobs:

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: consumers/token-price-service
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "consumers/token-price-service/app"

  tags:
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      token-price-tags: ${{ steps.docker-tags-token-price-service.outputs.tags }}
      token-price-labels: ${{ steps.docker-tags-token-price-service.outputs.labels }}
      token-price-json: ${{ steps.docker-tags-token-price-service.outputs.json }}
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0
      - name: Docker tags
        id: docker-tags-token-price-service
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: |
            docker.io/radixdlt/token-price-service
          tags: |
            type=sha,event=pr
            type=sha,event=branch
            type=semver,pattern={{version}}

  build:
    needs: 
    - tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "token-price-service"
      tags: |
          type=sha,event=pr
          type=sha,event=branch
          type=semver,pattern={{version}}
      context: "consumers/token-price-service"
      dockerfile: "consumers/token-price-service/Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: false
      snyk_target_ref: ${{ github.ref_name }}
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  deploy_pull_request:
    if: ${{ github.event.pull_request }}
    name: "Deploy PR"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.13.0
    needs:
      - tags
      - build
    with:
      env_name: pr
      hierarchical_namespace: token-price-ci-pr
      namespace: token-price-pr-${{ github.event.number }}
      create_subns: true
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: 'arn:aws:iam::308190735829:role/gh-token-price-pr-deployer'
      eks_cluster: rdx-works-main-dev
      helm_folder: "deploy/helm/token-price"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.token-price-json).labels['org.opencontainers.image.version'] }},
        ci.prNumber=${{ github.event.number }},
        ci.useLocalDb=true
      app_name: 'token-price'
      step_name: 'deploy-pr'

  deploy_dev:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    name: "Deploy DEV"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.13.0
    needs:
      - tags
      - build
    with:
      env_name: dev
      namespace: token-price-dev
      create_subns: false
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: 'arn:aws:iam::308190735829:role/gh-token-price-dev-deployer'
      eks_cluster: rdx-works-main-dev
      helm_folder: "deploy/helm/token-price"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.token-price-json).labels['org.opencontainers.image.version'] }}
      app_name: 'token-price'
      step_name: 'deploy-dev'

  deploy_prod:
    if: ${{ github.event_name == 'release' && github.event.release.prerelease == false }}
    name: "Deploy PROD"
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.13.0
    needs:
      - tags
      - build
    with:
      env_name: prod
      namespace: token-price-prod
      create_subns: false
      restart_pods: false
      aws_region: eu-west-2
      role_to_assume: 'arn:aws:iam::821496737932:role/gh-token-price-prod-deployer'
      eks_cluster: rdx-works-main-prod
      helm_folder: "deploy/helm/token-price"
      helmfile_extra_vars: >-
        ci.tag=${{ fromJSON(needs.tags.outputs.token-price-json).labels['org.opencontainers.image.version'] }}
      app_name: 'token-price'
      step_name: 'deploy-prod'
